// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using suaBaladaAqui2.Models;

#nullable disable

namespace suaBaladaAqui.Migrations
{
    [DbContext(typeof(suaBaladaAqui2Context))]
    [Migration("20220203154102_carousel")]
    partial class carousel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("suaBaladaAqui2.Models.CarouselModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FrasePrincipal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FraseSecundaria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Ordenacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("carousel");
                });

            modelBuilder.Entity("suaBaladaAqui2.Models.Efmigrationshistory", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("MigrationId")
                        .HasName("PRIMARY");

                    b.ToTable("__efmigrationshistory", (string)null);
                });

            modelBuilder.Entity("suaBaladaAqui2.Models.EventosModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Atracoes")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("atracoes");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("bairro");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cidade");

                    b.Property<DateTime>("DataEvento")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dataEvento");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("endereco");

                    b.Property<string>("Evento1")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("evento");

                    b.Property<string>("FoneContato")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("foneContato");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("imagem");

                    b.Property<string>("LocalName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("localName");

                    b.Property<string>("Organizador")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("organizador");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("responsavel");

                    b.HasKey("Id");

                    b.ToTable("eventos", (string)null);
                });

            modelBuilder.Entity("suaBaladaAqui2.Models.UsuariosModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<DateTime>("DataCadastro")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("usuarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
